twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
    globals:
        msg: '@App\Twig\msgExtension'
        read: '@App\Twig\msgExtension'
        allmessages: '@App\Twig\msgExtension'
        prod: '@App\Twig\ProdExtension'
        rest: '@App\Twig\RestExtension'
        rec: '@App\Twig\RecExtension'
        rep: '@App\Twig\RepExtension'
        nombreNotRead: '@App\Twig\msgExtension'
        res: '@App\Twig\ResExtension'
        eve: '@App\Twig\eveExtension'
